In [ ]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.9.2


In [ ]:
# Create tensors
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
tf.constant([1, 2, 3])

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [ ]:
# number of dimensions
scalar.ndim

0

In [ ]:
vector = tf.constant([10, 10])

In [ ]:
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
vector.ndim

1

In [ ]:
matrix = tf.constant([[10, 7],
                     [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
another_matrix = tf.constant([[10., 7.],
                     [7., 10.]], dtype=tf.float16)  # data type
another_matrix

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 7., 10.]], dtype=float16)>

In [ ]:
another_matrix.ndim

2

In [ ]:
matrix_1 = tf.constant([[10, 7, 4],
                     [7, 10, 5]])
matrix_1 

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[10,  7,  4],
       [ 7, 10,  5]], dtype=int32)>

In [ ]:
matrix_1.ndim
# tensor is an n-dimensional array of numbers

2

In [ ]:
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
unchangeable_tensor[0].assign(7)
unchangeable_tensor

AttributeError: ignored

In [ ]:
# creating random tensors
random_1 = tf.random.Generator.from_seed(7)  # set seed for reproducubility
random_1 = random_1.normal(shape=(3, 2))
random_2 = tf.random.Generator.from_seed(7)
random_2 = random_2.normal(shape=(3, 2))

random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [ ]:
# shuffle the order of elements in tensor
not_shuffled  = tf.constant([[10, 7],
                             [7, 10],
                             [3, 5]])
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10],
       [ 3,  5]], dtype=int32)>

In [ ]:
tf.random.set_seed(7)  # global level random seed
tf.random.shuffle(not_shuffled, seed=7)  # operation level random seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7, 10],
       [10,  7],
       [ 3,  5]], dtype=int32)>

In [ ]:
# other ways to create tensors
# create tensor with all ones
tf.ones([10, 7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
# create tensor with all zeros
tf.zeros(shape=(3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [ ]:
import numpy as np
numpy_A  = np.arange(1, 25, dtype=np.int32)  # create a NumPy array bet. 1 and 25
numpy_A

# capital for matrix or tensor, small for vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
# numpy array to tensor
A = tf.constant(numpy_A)
B = tf.constant(numpy_A, shape=(2, 3, 4))
A, B

(<tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>,
 <tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>)

In [ ]:
C = tf.constant(numpy_A, shape=(3, 8))
C

<tf.Tensor: shape=(3, 8), dtype=int32, numpy=
array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]], dtype=int32)>

In [ ]:
A.ndim

1

In [ ]:
B.ndim

3

### more information of tensors

* shape
* rank
* axis or deimension
* size

In [ ]:
rank_4_tensor  = tf.zeros(shape=(1, 2, 3, 4))
rank_4_tensor

<tf.Tensor: shape=(1, 2, 3, 4), dtype=float32, numpy=
array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor.ndim, rank_4_tensor.shape, tf.size(rank_4_tensor)

(4, TensorShape([1, 2, 3, 4]), <tf.Tensor: shape=(), dtype=int32, numpy=24>)

In [ ]:
print("Data type of every element:",rank_4_tensor.dtype)
print("No of dimensions (rank):",rank_4_tensor.ndim)
print("Shape  of tensor:",rank_4_tensor.shape)
print("Elements along the 0 axis:",rank_4_tensor.shape[0])
print("Elements along the last axis:",rank_4_tensor.shape[-1])
print("Total no. of elements in our tensor:",tf.size(rank_4_tensor))
print("Total no. of elements in our tensor:",tf.size(rank_4_tensor).numpy())

Data type of every element: <dtype: 'float32'>
No of dimensions (rank): 4
Shape  of tensor: (1, 2, 3, 4)
Elements along the 0 axis: 1
Elements along the last axis: 4
Total no. of elements in our tensor: tf.Tensor(24, shape=(), dtype=int32)
Total no. of elements in our tensor: 24


### Indexing tensors

In [ ]:
# first 2 elements
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(1, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
# first 2 elements - python lists
some_list = [1,  2,  3,  4]
some_list[:2]

[1, 2]

In [ ]:
# first element except for final one
rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 4), dtype=float32, numpy=array([[[[0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_2_tensor = tf.constant([[10, 7],
                            [3, 4]])
rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [ ]:
# last item of tensor
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [ ]:
some_list[-1]

4

In [ ]:
# add extra dimension
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [ ]:
# alternative
tf.expand_dims(rank_2_tensor, axis=-1)  #  -1  - expand in last

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [ ]:
tf.expand_dims(rank_2_tensor, axis=0)  # expand in 0 axis

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

### manipulating tensors


In [ ]:
tensor = tf.constant([[10, 7],
                     [3, 4]])
tensor +  10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [ ]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
tensor *  10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [ ]:
tensor / 2

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[5. , 3.5],
       [1.5, 2. ]])>

In [ ]:
tensor -  10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [ ]:
# alternatives
# using tf 9- built in function
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

### matrix multiplication

In [ ]:
# matmul in tf
tf.matmul(tensor, tensor)  # dot product

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
tensor * tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  16]], dtype=int32)>

In [ ]:
# matmul in python
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
X = tf.constant([[10, 7],
                [7, 10],
                [3, 5]])
Y  = tf.constant([[2, 4],
                  [7, 5],
                  [3, 4]])


In [ ]:
tf.reshape(Y, shape=(2, 3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[2, 4, 7],
       [5, 3, 4]], dtype=int32)>

In [ ]:
tf.matmul(X, tf.reshape(Y, shape=(2, 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[55, 61, 98],
       [64, 58, 89],
       [31, 27, 41]], dtype=int32)>

In [ ]:
X @ tf.reshape(Y, shape=(2, 3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[55, 61, 98],
       [64, 58, 89],
       [31, 27, 41]], dtype=int32)>

In [ ]:
# transpose
tf.transpose(X)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[10,  7,  3],
       [ 7, 10,  5]], dtype=int32)>

In [ ]:
tf.matmul(tf.transpose(X), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[78, 87],
       [99, 98]], dtype=int32)>

In [ ]:
# dot product
tf.tensordot(tf.transpose(X), Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[78, 87],
       [99, 98]], dtype=int32)>

In [ ]:
# changing the new tensor with default data type (float32)
B = tf.constant([1.7, 7.4])
B.dtype

tf.float32

In [ ]:
# reduced precision
D = tf.cast(B, dtype=tf.float16)
D, D.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>,
 tf.float16)

### Aggregating tensors

In [ ]:
E = tf.constant([-1, -9])
tf.abs(E)  # get absolute value

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 9], dtype=int32)>

* min
* max
* mean
* sum of tensor

In [ ]:
F = tf.constant(np.random.randint(0, 100, size=50))
F

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([87, 28, 51, 35, 76, 40, 74, 20, 59, 39,  8, 72, 39, 53, 77, 52, 31,
       83,  0, 93, 96,  1, 31,  1, 87, 70, 16, 80,  2, 63, 55, 12, 78, 66,
       24, 34, 30, 80, 79, 35, 61, 62, 97,  2, 75, 14,  6, 86, 81, 22])>

In [ ]:
tf.size(F), F.shape, F.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [ ]:
# find min
tf.reduce_min(F)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [ ]:
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=int64, numpy=97>

In [ ]:
tf.reduce_mean(F)

<tf.Tensor: shape=(), dtype=int64, numpy=49>

In [ ]:
tf.reduce_sum(F)

<tf.Tensor: shape=(), dtype=int64, numpy=2463>

In [ ]:
# variance
import tensorflow_probability as tfp
tfp.stats.variance(F)

<tf.Tensor: shape=(), dtype=int64, numpy=889>

In [ ]:
# standard deviation
tf.math.reduce_std(tf.cast(F, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=29.824696>

In [ ]:
# variance
tf.math.reduce_variance(tf.cast(F, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=889.51245>

### find positional max and min

In [ ]:
# create a new tensor for finding positional min and max
tf.random.set_seed(42)
G = tf.random.uniform(shape=[50])
G

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
# Find positional max
tf.argmax(G)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [ ]:
# Index on our largest value position
G[tf.argmax(G)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
# find max value of G
tf.reduce_max(G)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
# check equality
G[tf.argmax(G)] == tf.reduce_max(G)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [ ]:
# Find positional min
tf.argmin(G)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [ ]:
# Index on our largest value position
G[tf.argmin(G)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

### squeezing a tensor

In [ ]:
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [ ]:
G_squeezed = tf.squeeze(G)
G_squeezed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

### one hot encoding

In [ ]:
some_list = [0, 1, 2, 3]

tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
# custom values for one hot
tf.one_hot(some_list, depth=4, on_value="i love deep learning", off_value="I also like to sing")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'i love deep learning', b'I also like to sing',
        b'I also like to sing', b'I also like to sing'],
       [b'I also like to sing', b'i love deep learning',
        b'I also like to sing', b'I also like to sing'],
       [b'I also like to sing', b'I also like to sing',
        b'i love deep learning', b'I also like to sing'],
       [b'I also like to sing', b'I also like to sing',
        b'I also like to sing', b'i love deep learning']], dtype=object)>

### math operations

In [ ]:
H = tf.range(1, 10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:
tf.sqrt(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [ ]:
tf.math.log(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### Tensors and Numpy

In [ ]:
J = tf.constant(np.array([3., 6., 10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  6., 10.])>

In [ ]:
# turn tensor to numpy
np.array(J), type(np.array(J))

(array([ 3.,  6., 10.]), numpy.ndarray)

In [ ]:
J.numpy(), type(J.numpy())

(array([ 3.,  6., 10.]), numpy.ndarray)

In [ ]:
# default data types
numpy_J = tf.constant(np.array([3., 7., 10.]))
tensor_J = tf.constant([3., 7., 10.])
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)